---
sendgrid:
  from: <%= ENV['SG_FROM'] %>
  user: <%= ENV['SG_USER'] %>
  pass: <%= ENV['SG_KEY'] %>
  to:   <%= ENV['REVIEWER'] %>
  cc: dmitry.shmelev@onetwotrip.com
  subject: 'OTT-Infra: CodeReview'
jira:
  username: <%= ENV['JIRA_USERNAME'] %>
  password: <%= ENV['JIRA_PASSWORD'] %>
  site:     <%= ENV['JIRA_SITE'] %>
  issue:    <%= ENV['ISSUE'] %>
  auth_type: :basic
  context_path: ''
  tags:
    field: 'customfield_11001'
    deploy: 'Manual Deploy'
  excluded_projects:
    - 'Russian Railroad'
    - 'Hotels'
    - 'Servers & Services'
git:
  reviewer: <%= ENV['GITATTR_REVIEWER'] %>
  reviewer_key: <%= ENV.fetch('GITATTR_REVIEWER_KEY', 'reviewer.mail') %>
  workdir: <%= ENV.fetch('WORKDIR', './repos/') %>
